/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedExplainabilityRouteImport } from './routes/_authenticated/explainability'
import { Route as AuthenticatedImpactRouteImport } from './routes/_authenticated/impact'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedModelCardRouteImport } from './routes/_authenticated/model-card'
import { Route as AuthenticatedScoreRouteImport } from './routes/_authenticated/score'
import { Route as AuthenticatedWorklistRouteImport } from './routes/_authenticated/worklist'
import { Route as AuthenticatedDeclarationIdRouteImport } from './routes/_authenticated/declaration/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplainabilityRoute =
  AuthenticatedExplainabilityRouteImport.update({
    id: '/explainability',
    path: '/explainability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpactRoute = AuthenticatedImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelCardRoute = AuthenticatedModelCardRouteImport.update({
  id: '/model-card',
  path: '/model-card',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoreRoute = AuthenticatedScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorklistRoute = AuthenticatedWorklistRouteImport.update({
  id: '/worklist',
  path: '/worklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeclarationIdRoute =
  AuthenticatedDeclarationIdRouteImport.update({
    id: '/declaration/$id',
    path: '/declaration/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof AuthenticatedAboutRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/explainability': typeof AuthenticatedExplainabilityRoute
  '/impact': typeof AuthenticatedImpactRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/lab': typeof AuthenticatedLabRoute
  '/model-card': typeof AuthenticatedModelCardRoute
  '/score': typeof AuthenticatedScoreRoute
  '/worklist': typeof AuthenticatedWorklistRoute
  '/declaration/$id': typeof AuthenticatedDeclarationIdRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof AuthenticatedAboutRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/explainability': typeof AuthenticatedExplainabilityRoute
  '/impact': typeof AuthenticatedImpactRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/lab': typeof AuthenticatedLabRoute
  '/model-card': typeof AuthenticatedModelCardRoute
  '/score': typeof AuthenticatedScoreRoute
  '/worklist': typeof AuthenticatedWorklistRoute
  '/': typeof AuthenticatedIndexRoute
  '/declaration/$id': typeof AuthenticatedDeclarationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/explainability': typeof AuthenticatedExplainabilityRoute
  '/_authenticated/impact': typeof AuthenticatedImpactRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/model-card': typeof AuthenticatedModelCardRoute
  '/_authenticated/score': typeof AuthenticatedScoreRoute
  '/_authenticated/worklist': typeof AuthenticatedWorklistRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/declaration/$id': typeof AuthenticatedDeclarationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/assistant'
    | '/explainability'
    | '/impact'
    | '/journal'
    | '/lab'
    | '/model-card'
    | '/score'
    | '/worklist'
    | '/declaration/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/assistant'
    | '/explainability'
    | '/impact'
    | '/journal'
    | '/lab'
    | '/model-card'
    | '/score'
    | '/worklist'
    | '/'
    | '/declaration/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/about'
    | '/_authenticated/assistant'
    | '/_authenticated/explainability'
    | '/_authenticated/impact'
    | '/_authenticated/journal'
    | '/_authenticated/lab'
    | '/_authenticated/model-card'
    | '/_authenticated/score'
    | '/_authenticated/worklist'
    | '/_authenticated/'
    | '/_authenticated/declaration/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explainability': {
      id: '/_authenticated/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof AuthenticatedExplainabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impact': {
      id: '/_authenticated/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AuthenticatedImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-card': {
      id: '/_authenticated/model-card'
      path: '/model-card'
      fullPath: '/model-card'
      preLoaderRoute: typeof AuthenticatedModelCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/score': {
      id: '/_authenticated/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof AuthenticatedScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worklist': {
      id: '/_authenticated/worklist'
      path: '/worklist'
      fullPath: '/worklist'
      preLoaderRoute: typeof AuthenticatedWorklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/declaration/$id': {
      id: '/_authenticated/declaration/$id'
      path: '/declaration/$id'
      fullPath: '/declaration/$id'
      preLoaderRoute: typeof AuthenticatedDeclarationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedExplainabilityRoute: typeof AuthenticatedExplainabilityRoute
  AuthenticatedImpactRoute: typeof AuthenticatedImpactRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedModelCardRoute: typeof AuthenticatedModelCardRoute
  AuthenticatedScoreRoute: typeof AuthenticatedScoreRoute
  AuthenticatedWorklistRoute: typeof AuthenticatedWorklistRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeclarationIdRoute: typeof AuthenticatedDeclarationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedExplainabilityRoute: AuthenticatedExplainabilityRoute,
  AuthenticatedImpactRoute: AuthenticatedImpactRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedModelCardRoute: AuthenticatedModelCardRoute,
  AuthenticatedScoreRoute: AuthenticatedScoreRoute,
  AuthenticatedWorklistRoute: AuthenticatedWorklistRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeclarationIdRoute: AuthenticatedDeclarationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
